name: isb-mtm
channels:
    - defaults
dependencies:
    - bzip2=1.0.8
    - ca-certificates=2024.3.11
    - libffi=3.4.4
    - openssl=3.0.13
    - pip=24.0
    - python=3.11.8
    - setuptools=69.5.1
    - sqlite=3.45.3
    - tk=8.6.14
    - vc=14.2
    - vs2015_runtime=14.29.30133
    - wheel=0.43.0
    - xz=5.4.6
    - zlib=1.2.13
    - pip:
          - configparser==7.0.0
          - imageio==2.34.1
          - lazy-loader==0.4
          - mss==9.0.1
          - multi-template-matching==1.6.6
          - networkx==3.3
          - numpy==1.26.4
          - opencv-python==4.9.0.80
          - opencv-python-headless==4.9.0.80
          - packaging==24.0
          - pandas==2.2.2
          - pillow==10.3.0
          - psutil==5.9.8
          - python-dateutil==2.9.0.post0
          - pytz==2024.1
          - pywin32==306
          - scikit-image==0.23.2
          - scipy==1.13.1
          - six==1.16.0
          - tifffile==2024.5.22
          - tzdata==2024.1
